// <auto-generated />
using LiveRecorder.NET.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LiveRecorder.NET.Migrations
{
    [DbContext(typeof(AcfunlivedbDbContext))]
    [Migration("20250627071923_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.17");

            modelBuilder.Entity("LiveRecorder.NET.Models.Acfun.AcfunLive", b =>
                {
                    b.Property<string>("liveId")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("startTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("streamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("uid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("url")
                        .HasColumnType("TEXT");

                    b.Property<string>("url_backup")
                        .HasColumnType("TEXT");

                    b.HasKey("liveId");

                    b.HasIndex("startTime");

                    b.HasIndex("uid");

                    b.ToTable("Lives");
                });
#pragma warning restore 612, 618
        }
    }
}
